version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  reviewers:
  - itorisaias
  ignore:
  - dependency-name: ecto_sql
    versions:
    - 3.6.0
  - dependency-name: hackney
    versions:
    - 1.17.1
    - 1.17.2
    - 1.17.3
  - dependency-name: ex_machina
    versions:
    - 2.7.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
