version: 1
update_configs:
  - package_manager: "elixir:hex"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "itorisaias"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
